base:
  project: insurance-project
  random_state: 42
  target_col: charges

data_source:
  s3_source: data_given/insurance.csv

load_data:
  raw_dataset_csv: data/raw/insurance.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.1

estimators:
  rfr:
    params:
      max_depth: 3
      min_samples_split: 5
      n_estimators: 120

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib
